version: '3'
services:
  api:
    build:
      context: api
      dockerfile: Dockerfile.development
    links:
      - database
    ports:
      - 4000:4000
    volumes:
      - ./api/src:/usr/src/app/src
  database:
    image: postgres:alpine
    environment:
      POSTGRES_DB: omniboard
    expose:
      - 5432
