version: '3'
services:
  api:
    build: api
    entrypoint:
      - yarn
      - start
    environment:
      - NODE_ENV=development
    links:
      - database
    ports:
      - '4000:4000'
    volumes:
      - './api/src:/usr/src/app/src'
  database:
    image: 'postgres:alpine'
    environment:
      POSTGRES_DB: omniboard
      POSTGRES_USER: postgres
    expose:
      - '5432'
