[build]
  command = "cd client && yarn build"
  publish = "client/dist"
  [build.environment]
    API_ORIGIN = "/api"
[[headers]]
  for = "*"
  [headers.values]
    Content-Security-Policy = "frame-ancestors 'none'"
[[headers]]
  for = "src.*.(css|js)"
  [headers.values]
    Cache-Control = "public,max-age=31536000,immutable"
[[redirects]]
  from = "api/*"
  status = 200
  to = "http://ec2-100-26-29-192.compute-1.amazonaws.com:4000/:splat"
[[redirects]]
  from = "*"
  status = 200
  to = "/"
