[build]
  command = "cd client && yarn build"
  publish = "client/dist"
[[headers]]
  for = "*"
  [headers.values]
    Content-Security-Policy = "frame-ancestors 'none'"
[[headers]]
  for = "src.*.(css|js)"
  [headers.values]
    Cache-Control = "public,max-age=31536000,immutable"
[[redirects]]
  from = "*"
  status = 200
  to = "/"
