CREATE TABLE IF NOT EXISTS posts(
	body TEXT NOT NULL,
	created_at TIMESTAMPTZ NOT NULl DEFAULT NOW(),
	id SERIAL PRIMARY KEY,
	location TEXT NOT NULL,
	title TEXT NOT NULL,
	user_id TEXT NOT NULL
);
